universe                = vanilla

executable              = run_genie_production_apptainer.sh

#arguments               = -n 10000 -p $(ProcId) -c 100000 -t Ti -T G21_11b_00_000 -e 8 -o /eos/user/w/wketchum/ldmx_en_samples/production_06Nov2024/ldmx_genie_G21_11b_00_000_Ti_8GeV
#arguments               = -n 10000 -p $(ProcId) -c 110000 -t Ti -T G18_02a_00_000 -e 8 -o /eos/user/w/wketchum/ldmx_en_samples/production_06Nov2024/ldmx_genie_G18_02a_00_000_Ti_8GeV
#arguments               = -n 10000 -p $(ProcId) -c 120000 -t Ti -T G18_02a_02_11b -e 8 -o /eos/user/w/wketchum/ldmx_en_samples/production_06Nov2024/ldmx_genie_G18_02a_02_11b_Ti_8GeV
#arguments               = -n 10000 -p $(ProcId) -c 130000 -t Ti -T G18_02b_00_000 -e 8 -o /eos/user/w/wketchum/ldmx_en_samples/production_06Nov2024/ldmx_genie_G18_02b_00_000_Ti_8GeV
arguments               = -n 10000 -p $(ProcId) -c 140000 -t Ti -T G18_02b_02_11b -e 8 -o /eos/user/w/wketchum/ldmx_en_samples/production_06Nov2024/ldmx_genie_G18_02b_02_11b_Ti_8GeV

output                  = logs/ldmx_genie_prod.$(ClusterId).$(ProcId).out
error                   = logs/ldmx_genie_prod.$(ClusterId).$(ProcId).err
log                     = logs/ldmx_genie_prod.$(ClusterId).$(ProcId).log

request_cpus   = 1
#request_memory = 2000M
#request_disk   = 10240M

#+MaxRuntime   = 7200
+JobFlavour  = "workday"

queue 200
