###############################################################################
# This dockerfile is meant to build the production image of ldmx-sw
#   for the development image, look at the LDMX-Software/docker repo
###############################################################################

#FROM ghcr.io/wesketchum/ldmxsw:latest
FROM ghcr.io/wesketchum/ldmx/dev:hepmc

ARG NPROC=1

# install ldmx-sw into the container at /usr/local and rebuild
COPY --from=ldmx-sw ldmx-sw /code
RUN mkdir -p /code/build &&\
    rm -rf /code/build/* &&\
    /etc/entry.sh /code/build cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. &&\
    /etc/entry.sh /code/build make -j${NPROC} install &&\
    rm -rf code &&\
    ldconfig /usr/local/lib

ENV LDMX_SW_INSTALL=/usr/local

#copy in ldmx-genie-splines
COPY ldmx-genie-splines /ldmx-genie-splines

#setup LDMX_eN_GENIE scripts and analysis dirs
WORKDIR /LDMX_eN_GENIE
COPY scripts /LDMX_eN_GENIE/scripts
COPY ldmxsw_configs /LDMX_eN_GENIE/ldmxsw_configs
COPY analysis /LDMX_eN_GENIE/analysis
COPY propagationMap.root /LDMX_eN_GENIE/propagationMap.root

#need to make executable script executable
RUN chmod a+x /LDMX_eN_GENIE/scripts/run_genie_sim_and_reco.sh

#working area. Needs to be non-root-user writeable
WORKDIR /work
RUN chmod a+rwX -R /work
ENTRYPOINT ["/etc/entry.sh",".","/LDMX_eN_GENIE/scripts/run_genie_sim_and_reco.sh"]