###############################################################################
# This dockerfile is meant to build the production image of ldmx-sw
#   for the development image, look at the LDMX-Software/docker repo
###############################################################################

FROM ghcr.io/wesketchum/ldmxsw:latest

ARG NPROC=1

# install ldmx-sw into the container at /usr/local
COPY ldmx-sw /code
RUN mkdir -p /code/build &&\
    rm -rf /code/build/* &&\
    /etc/entry.sh /code/build cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. &&\
    /etc/entry.sh /code/build make -j${NPROC} install &&\
    rm -rf code &&\
    ldconfig /usr/local/lib

ENV LDMX_SW_INSTALL=/usr/local

#pull down ldmx-genie-splines
WORKDIR /ldmx-genie-splines
RUN wget -q https://github.com/wesketchum/ldmx-genie-splines/archive/refs/heads/main.tar.gz &&\
    tar xzf main.tar.gz --strip-components 1

#pull down LDMX_eN_GENIE
#WORKDIR /LDMX_eN_GENIE
#RUN wget -q https://github.com/wesketchum/LDMX_eN_GENIE/archive/refs/heads/main.tar.gz &&\
#    tar xzf main.tar.gz --strip-components 1
#WORKDIR /LDMX_eN_GENIE
COPY LDMX_eN_GENIE /LDMX_eN_GENIE

#directory for placing output. Needs to be mounted.
#VOLUME /output

WORKDIR /
ENTRYPOINT ["/etc/entry.sh",".","/LDMX_eN_GENIE/scripts/run_genie_sim_and_reco.sh"]